# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "https://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sihong Park 
user_description: Web Developer 
user_title: Web Developer 
email: pozt1234@gamil.com 
#twitter_username: lorem_ipsum
github_username: Sihong12 
#gplus_username:  lorem_ipsum
disqus_username: pozt1234 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Posts
    url: /Posts
  - title: 
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
